"""Export model_int8.tflite and TEST samples as C headers for the Arduino sketch.

Run from the project root:
    python -m src.export_arduino          # first N_SAMPLES_FIRST_RUN test samples (Step 8)
    python -m src.export_arduino --all    # all test samples (Step 9)
Writes firmware/gunpoint_tflm/model_data.h, test_data.h and results/export_manifest.json.
"""

import argparse       # --all switch
import hashlib        # SHA-256 fingerprint of the exported model bytes
import json           # results/export_manifest.json
import datetime       # timestamp in the manifest
import numpy as np    # test samples

import config                         # paths, class names, N_SAMPLES_FIRST_RUN
from src.dataset import load_all      # TEST split (same order as pc_predictions.csv)

INT8_TFLITE = config.MODELS_DIR / "model_int8.tflite"
MODEL_H = config.FIRMWARE_DIR / "model_data.h"
TEST_H = config.FIRMWARE_DIR / "test_data.h"
MANIFEST = config.RESULTS_DIR / "export_manifest.json"


def write_model_header(model_bytes, sha256_hex):
    """model bytes -> C array. alignas(16): TFLM reads the flatbuffer in place and wants it aligned."""
    lines = [
        "// GENERATED by src/export_arduino.py - do not edit.",
        f"// source: {INT8_TFLITE.name}, {len(model_bytes)} bytes, sha256 {sha256_hex}",
        "#pragma once",
        "",
        f'#define G_MODEL_SHA256 "{sha256_hex}"   // expected fingerprint; the board recomputes and compares',
        "",
        "alignas(16) const unsigned char g_model[] = {",
    ]
    for i in range(0, len(model_bytes), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in model_bytes[i:i + 12])
        lines.append(f"  {chunk},")
    lines += ["};", f"const unsigned int g_model_len = {len(model_bytes)};", ""]
    MODEL_H.write_text("\n".join(lines))


def write_test_header(X, y, indices):
    """Test samples as float arrays. %.9g + 'f' suffix reproduces the exact float32 values."""
    n, L = X.shape
    lines = [
        "// GENERATED by src/export_arduino.py - do not edit.",
        f"// {n} samples of the official GunPoint TEST split, indices {indices[0]}..{indices[-1]}, no preprocessing.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"const int kSeriesLength = {L};",
        f"const int kNumSamples = {n};",
        f"const int kNumClasses = {len(config.CLASS_NAMES)};",
        "const char* const kClassNames[] = {" + ", ".join(f'"{c}"' for c in config.CLASS_NAMES) + "};",
        "",
        "// Position in the TEST split (matches the idx column of results/pc_predictions.csv).",
        "const uint16_t kTestIndex[kNumSamples] = {" + ", ".join(str(i) for i in indices) + "};",
        "// True label, 0 = " + config.CLASS_NAMES[0] + ", 1 = " + config.CLASS_NAMES[1] + ".",
        "const int8_t kTestLabels[kNumSamples] = {" + ", ".join(str(int(v)) for v in y) + "};",
        "",
        "const float kTestData[kNumSamples][kSeriesLength] = {",
    ]
    for i in range(n):
        vals = [f"{float(v):.9g}f" for v in X[i]]
        lines.append(f"  {{  // sample {indices[i]}, label {int(y[i])}")
        for j in range(0, L, 10):
            lines.append("    " + ", ".join(vals[j:j + 10]) + ",")
        lines.append("  },")
    lines += ["};", ""]
    TEST_H.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--all", action="store_true", help="export all TEST samples instead of the first few")
    args = parser.parse_args()

    d = load_all()
    n = len(d["y_test"]) if args.all else config.N_SAMPLES_FIRST_RUN
    X, y = d["X_test"][:n].astype(np.float32), d["y_test"][:n]
    indices = list(range(n))

    model_bytes = INT8_TFLITE.read_bytes()
    sha256_hex = hashlib.sha256(model_bytes).hexdigest()

    config.FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)
    config.RESULTS_DIR.mkdir(exist_ok=True)
    write_model_header(model_bytes, sha256_hex)
    write_test_header(X, y, indices)

    manifest = {
        "exported_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "model_file": INT8_TFLITE.name,
        "model_bytes": len(model_bytes),
        "model_sha256": sha256_hex,
        "n_samples": n,
        "series_length": int(X.shape[1]),
        "sample_indices": indices,
        "class_names": config.CLASS_NAMES,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2))

    print(f"model   : {len(model_bytes)} bytes, sha256 {sha256_hex}")
    print(f"samples : {n} x {X.shape[1]} floats, labels {y.tolist() if n <= 10 else str(y[:10].tolist()) + '...'}")
    print(f"wrote   : {MODEL_H}  ({MODEL_H.stat().st_size} bytes of text)")
    print(f"wrote   : {TEST_H}  ({TEST_H.stat().st_size} bytes of text)")
    print(f"wrote   : {MANIFEST}")


if __name__ == "__main__":
    main()